### ISSUE TITLE
Some overlap on Tilix's window

### ISSUE THREAD

**Issue by canha** [Fausto-Korpsvart/Everforest-GTK-Theme#2]
Hi, thanks for the work on this theme!

I've noticed that Tilix doesn't seem to respect the bottom rounded borders, is there anything that can be done? I'm using the borderless theme on Arch Linux (aur/everforest-gtk-theme-git r13.78f48292-1)

Kind regards.

![image](https://user-images.githubusercontent.com/470227/182496629-0ed1c777-0c89-449a-a1a9-d979adadb91b.png)

**Comment by Fausto-Korpsvart** [comment]
> Hi, thanks for the work on this theme!
> 
> I've noticed that Tilix doesn't seem to respect the bottom rounded borders, is there anything that can be done? I'm using the borderless theme on Arch Linux (aur/everforest-gtk-theme-git r13.78f48292-1)
> 
> Kind regards.
> 
> ![image](https://user-images.githubusercontent.com/470227/182496629-0ed1c777-0c89-449a-a1a9-d979adadb91b.png)

Hi, @canha.

That's weird, I don't understand why in your configuration the bottom rounded corners are not applied.
In any case, I will check to correct the error. Thank you for reporting and your support. };-]

This is my configuration in Tilix, I hope it can help. 
![Everforest-Tilix](https://user-images.githubusercontent.com/47998118/182507958-57393be3-cd04-4765-82cb-3e9b2ab91198.png)

**Comment by canha** [comment]
Thanks for getting back to me.

That configuration helped figure it:
![image](https://user-images.githubusercontent.com/470227/182602588-9e913431-fc3f-43de-ac3d-6dd026ddac53.png)

That option, you have it enabled and I don't. Not using the tabs will apparently cause this.

**Comment by Fausto-Korpsvart** [comment]
> Thanks for getting back to me.
> 
> That configuration helped figuring it out: ![image](https://user-images.githubusercontent.com/470227/182602588-9e913431-fc3f-43de-ac3d-6dd026ddac53.png)
> 
> That option, you have it enabled and I don't. Not using the tabs will apparently cause this.

Really? That simple option? I've always used that configuration in Tilix because you can place the tabs at the bottom, which in Gnome Terminal you can't do, and I don't like to have a sidebar with tabs because it takes a lot of space, just like the tabs at the top, I like to have enough space inside the terminal to be able to work, and based on this configuration is that I made the rounded corners at the bottom.
I don't really understand what the difference is, I will check again to fix the problem, thanks for reporting.
