### ISSUE TITLE
Gnome status menu: buttons overlap

### ISSUE THREAD

**Issue by chfreundchen** [Fausto-Korpsvart/Everforest-GTK-Theme#21]
the buttons in the status menu overlap. the rightmost part of each button, used for selecting further options, starts where the full button should end (maybe not quite clear from words, thus the attached picture.)

Fedora 41, Gnome 47.

![Screenshot From 2024-11-17 22-51-22](https://github.com/user-attachments/assets/79d15b3a-ada1-4d07-841c-1cb3e7dd57dd)

**Comment by Fausto-Korpsvart** [comment]
> the buttons in the status menu overlap. the rightmost part of each button, used for selecting further options, starts where the full button should end (maybe not quite clear from words, thus the attached picture.)
> 
> Fedora 41, Gnome 47.


From which source did you install the theme?
Because this only happens with older themes, make sure you install the theme from Pling or from this repository.

This is what the updated theme looks like, I also use Fedora, and I'm on version 41 with Gnome 47.

![F41-G47-QS](https://github.com/user-attachments/assets/a00349ff-8018-4ba9-b02b-1b1793236eea)

**Comment by chfreundchen** [comment]
... and indeed I had downloaded the new version but had still used an old version, d'uh... sorry about that, and thanks for the theme!

**Comment by chfreundchen** [comment]
my mistake. i had not installed the latest version...
